base_model: "/data1/WM_workspace/checkpoints/qwen2-1.5b/"
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: "/data1/WM_workspace/datasets/process-pku-30k/"
    conversation: qwen-7b-chat
    type: sharegpt.load_ultrachat
    split: "train"
    train_on_split: "train"

warmup_steps: 40
val_set_size: 0.0
output_dir: /data1/WM_workspace/checkpoints/qwen2-1.5b-bs128_lr1e-5

wandb_project: preference-models
wandb_model: online
#wandb_entity: domain-generalization
wandb_watch:
wandb_name: "qwen2-1.5b_bs128_lr1e-5"
#_response_only
wandb_log_model:

train_on_inputs: false

save_safetensors: true
#noisy_embedding_alpha: 10.0 # default for sharegpt type
dataset_prepared_path: "/data1/WM_workspace/datasets/process-pku-30k/"


dataset_processes: 48
#torch_compile: true
sequence_len: 3072
sample_packing: true
pad_to_sequence_len: true

trust_remote_code: True
adapter:
lora_model_dir:


gradient_checkpointing: false

#warmup_ratio: 0.1
gradient_accumulation_steps: 16
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 1.e-5

weight_decay: 0.0
max_grad_norm: 1.0


group_by_length: false
bf16: auto
fp16: false
tf32: true

early_stopping_patience:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true


eval_steps:
eval_table_size:
eval_table_max_new_tokens:
#save_steps: 100
save_strategy: "epoch"
save_total_limit: 1
debug:


ddp: #true
deepspeed: /data1/WM_workspace/RLHF-Reward-Modeling/deepspeed_configs/deepspeed_1.json # multi-gpu only

fsdp:
fsdp_config:
special_tokens:

